name: release
on:
  push:
    tags:
      - "*"
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/bundle/release/app-release.aab
