name: release
on:
  push:
    tags:
      - "*"
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0
      - run: flutter pub get
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          path: build/outputs/bundle/release/app-release.aab
